apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dt-broker
  description: Enabling event communication, enforcing FIFO ordering
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: guest
  system: digital-twin
  providesApis:
    - binary-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: binary-api
  description: An binary API for communicating
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/documentation: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
  links:
    - url: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
      title: Dummy V1.0 Spec
      icon: link
    - url: https://www.princexml.com/samples/
      title: Digital Documentation
      icon: link
spec:
  type: link 
  lifecycle: development
  owner: guest
  system: digital-twin
  unsafeUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
  embed: true
  definition: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'