apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: GRPCProject
  description: GRPC Project.
  #annotations:
    #backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition: 
    $text: ./swagger.json
