apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api-beta
  description: 2# CATALOG V2 - A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition: 
    $text: http://localhost:5036/swagger/v1/swagger.json # Path to the OpenAPI definition file
