apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api-beta
  description: 2# CATALOG V2 - A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition: https://github.com/parmendes/API_Doc/blob/main/apis/subsystem-beta/ervice-or-component/WeatherForecastAPI.yaml # Path to the OpenAPI definition file
