app:
  # Title of the Backstage application
  title: Scaffolded Backstage App
  # Base URL where the app is hosted
  baseUrl: http://localhost:3000

organization:
  # Name of the organization using this Backstage instance
  name: My Company

backend:
  logging:
      # Logging level for the backend (e.g., debug, info, warn, error)
      level: debug
  # Base URL for the backend service
  baseUrl: http://localhost:7007
  listen:
    # Port where the backend listens for requests
    port: 7007
  csp:
    # Content Security Policy settings for the backend
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    # CORS settings to allow requests from specific origins
    origin: 
      - "http://localhost:3000"
      - "http://localhost:5036"
    # HTTP methods allowed for CORS
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    # Allow credentials (e.g., cookies) in CORS requests
    credentials: true
  database:
    # Database configuration for local development
    client: better-sqlite3
    connection: ':memory:'
  reading:
    # Hosts allowed for reading data
    allow:
      - host: '127.0.0.1:7293'
      - host: '127.0.0.1:5036'

integrations:
  github:
    - host: github.com
      # GitHub Personal Access Token (PAT) for authentication
      token: ${GITHUB_TOKEN}

techdocs:
  # Configuration for TechDocs, Backstage's documentation feature
  builder: 'local' # Options: 'local', 'external'
  generator:
    # Determines where the TechDocs generator runs
    runIn: 'docker' # Options: 'docker', 'local'
  publisher:
    # Where the generated documentation is published
    type: 'local' # Options: 'local', 'googleGcs', 'awsS3'

auth:
  providers:
    # Guest authentication provider for unauthenticated users
    guest: {}

scaffolder:
  # Configuration for software templates used in scaffolding new projects

catalog:
  locations:
    # Remote YAML files defining catalog entities
    - type: url
      target: https://github.com/parmendes/API_Doc/tree/main/apis/*/*/*.yaml
    # Local example data for testing
    - type: file
      target: ../../examples/entities.yaml
    # Local example template for scaffolding
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
  # Enable URL readers for searching catalog entities
  useUrlReadersSearch: true

permission:
  # Enable or disable the permission framework
  enabled: true