openapi: 3.0.4
info:
  title: MinimalRestAPI_1.0
  description: "### MinimalRestAPI\n\nAn internal API for managing weather forecasts. This API is not intended for external use and is rate-limited to 100 requests per minute for free users.\n\n#### Notes:\n- Authentication is required for most operations.\n- Ensure proper usage of the API within the defined rate limits."
  contact:
    name: MinimalRestAPI
    email: ''
  license:
    name: Use under MIT
  version: '1.0'
paths:
  /api/v1/weatherforecast/weatherforecast:
    get:
      tags:
        - WeatherForecast
      summary: Retrieves the weather forecast for the next 5 days.
      description: Returns a list of weather forecasts with temperatures and summaries.
      operationId: GetWeatherForecast
      parameters:
        - name: minTemperature
          in: query
          required: true
          schema:
            type: integer
            format: int32
            default: -20
        - name: maxTemperature
          in: query
          required: true
          schema:
            type: integer
            format: int32
            default: 55
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Invalid temperature range.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
  /api/v1/weatherforecast/weatherforecast/legacy:
    get:
      tags:
        - WeatherForecast
      summary: Legacy endpoint (deprecated).
      description: This endpoint is deprecated. Use '/weatherforecast' instead.
      operationId: GetLegacyWeatherForecast
      responses:
        '200':
          description: OK
      deprecated: true
  /api/v1/weatherforecast/weatherforecast/admin-endpoint:
    post:
      tags:
        - WeatherForecast
      summary: Creates a new weather forecast (Admin only).
      description: Only users with Admin privileges can access this endpoint.
      operationId: CreateWeatherForecastADMIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
        required: true
      responses:
        '201':
          description: Created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized access.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
  /api/v1/weatherforecast/weatherforecast/user-endpoint:
    post:
      tags:
        - WeatherForecast
      summary: Creates a new weather forecast.
      description: Authenticated users can create forecasts.
      operationId: CreateWeatherForecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
        required: true
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          description: Gets the date of the weather forecast.
          format: date
        temperatureC:
          maximum: 50
          minimum: -50
          type: integer
          description: Gets the temperature in Celsius.
          format: int32
          default: 15
        temperatureF:
          type: integer
          description: Gets the temperature in Fahrenheit.
          format: int32
          readOnly: true
        summary:
          maxLength: 100
          minLength: 0
          type: string
          description: Gets the summary of the forecast.
          default: Default summary
          nullable: true
      additionalProperties: false
      description: Represents a weather forecast record.
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://localhost:5001/connect/token
          scopes:
            api1: Access MinimalRestAPI
security:
  - oauth2:
      - api1
