openapi: 3.0.4
info:
  title: MinimalRestAPI
  description: "### MinimalRestAPI\n\nAn internal API for managing weather forecasts. This API is not intended for external use and is rate-limited to 100 requests per minute for free users.\n\n#### Features:\n- Retrieve weather forecasts for the next 5 days.\n- Create new weather forecasts.\n- Update existing weather forecasts.\n- Delete weather forecasts.\n\n#### Notes:\n- Authentication is required for most operations.\n- Ensure proper usage of the API within the defined rate limits."
  version: v2.0
paths:
  /weatherforecast:
    get:
      tags:
        - MinimalRestAPI
      summary: Retrieves the weather forecast for the next 5 days.
      description: 'This endpoint provides a list of weather forecasts for the next 5 days, including temperature and summary.'
      operationId: GetWeatherForecast
      parameters:
        - name: minTemperature
          in: query
          required: true
          schema:
            type: integer
            format: int32
            default: -20
        - name: maxTemperature
          in: query
          required: true
          schema:
            type: integer
            format: int32
            default: 55
      responses:
        '200':
          description: A list of weather forecasts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Bad request. The input parameters are invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error. Something went wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
  /v0.9/weatherforecast:
    get:
      tags:
        - MinimalRestAPI
      summary: Legacy weather forecast (v0.9)
      description: This is a legacy version of the weather forecast endpoint (before v1). Returns 3 days only.
      operationId: GetWeatherForecastV0_9
      responses:
        '200':
          description: Weather forecast (legacy format).
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      deprecated: true
  /weatherforecast/legacy:
    get:
      tags:
        - MinimalRestAPI
      description: This endpoint is deprecated. Use /weatherforecast instead.
      operationId: GetLegacyWeatherForecast
      responses:
        '200':
          description: OK
      deprecated: true
  /weatherforecast/admin-endpoint:
    post:
      tags:
        - MinimalRestAPI
      summary: Creates a new weather forecast.
      description: This endpoint allows authenticated users to create a new weather forecast.
      operationId: CreateWeatherForecastADMIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
        required: true
      responses:
        '201':
          description: Weather forecast created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Bad request. The input parameters are invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized. The user is not authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error. Something went wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
        - Bearer: [ ]
  /weatherforecast/user-endpoint:
    post:
      tags:
        - MinimalRestAPI
      summary: Creates a new weather forecast.
      description: This endpoint allows authenticated users to create a new weather forecast.
      operationId: CreateWeatherForecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
        required: true
      responses:
        '201':
          description: Weather forecast created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Bad request. The input parameters are invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized. The user is not authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error. Something went wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
        - Bearer: [ ]
  '/weatherforecast/{date}':
    put:
      tags:
        - MinimalRestAPI
      summary: Updates an existing weather forecast.
      description: This endpoint allows authenticated users to update an existing weather forecast.
      operationId: UpdateWeatherForecast
      parameters:
        - name: date (Example - non-existent)
          in: path
          description: 'The date of the weather forecast to update. Format: yyyy-MM-dd'
          required: true
          schema:
            pattern: '^\d{4}-\d{2}-\d{2}$'
            type: string
            format: date
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
            example:
              date: '2025-04-24'
              temperatureC: 30
              summary: Partly Cloudy
        required: true
      responses:
        '200':
          description: Weather forecast updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Bad request. The input parameters are invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized. The user is not authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '404':
          description: Not found. The weather forecast for the specified date was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error. Something went wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
        - Bearer: [ ]
    delete:
      tags:
        - MinimalRestAPI
      summary: Deletes a weather forecast.
      description: This endpoint allows authenticated users to delete a weather forecast by date.
      operationId: DeleteWeatherForecast
      parameters:
        - name: date
          in: path
          description: 'The date of the weather forecast to delete. Format: yyyy-MM-dd'
          required: true
          schema:
            pattern: '^\d{4}-\d{2}-\d{2}$'
            type: string
            format: date
      responses:
        '204':
          description: No content. The weather forecast was deleted successfully.
        '400':
          description: Bad request. The input parameters are invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '401':
          description: Unauthorized. The user is not authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '404':
          description: Not found. The weather forecast for the specified date was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
        '500':
          description: Internal server error. Something went wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    format: int32
                  detail:
                    type: string
                  instance:
                    type: string
      security:
        - Bearer: [ ]
        - Bearer: [ ]
        - Bearer: [ ]
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        temperatureF:
          type: integer
          description: Gets the temperature in Fahrenheit.
          format: int32
          readOnly: true
        date:
          type: string
          description: Gets the date of the weather forecast.
          format: date
        temperatureC:
          maximum: 50
          minimum: -50
          type: integer
          description: Gets the temperature in Celsius.
          format: int32
          default: 15
        summary:
          maxLength: 100
          minLength: 0
          type: string
          description: Gets the summary of the weather forecast.
          default: Default summary
          nullable: true
      additionalProperties: false
      description: Represents a weather forecast.
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://localhost:5001/connect/token
          scopes:
            api1: Access MinimalRestAPI
security:
  - oauth2:
      - api1
