apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api-alphav1
  description: Wildcard - A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition: 
    $text: http://127.0.0.1:5036/swagger/v1/swagger.json

---
apiVersion: backstage.io/v2alpha1
kind: API
metadata:
  name: my-backstage-api-alphav2
  description: Wildcard - A REST API with Swashbuckle and NSwag (v2).
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition: 
    $text: http://127.0.0.1:5036/swagger/v1/swagger.json
